### ISSUE TITLE
Dragging bars does not seem to work

### ISSUE THREAD

**Issue by kolaente** [InfectoOne/vue-ganttastic#10]
I'm currently trying to include ganttastic in an existing application. I'm using it something like this:

```vue
		<g-gantt-chart
			:chart-start="dateFrom.toString()"
			:chart-end="dateTo.toString()"
			:push-on-overlap="true"
			row-label-width="0"
			:grid="true"
			@dragend-bar="dragged($event)"
		>
			<g-gantt-row
				v-for="(t, k) in theTasks"
				:key="t ? t.id : 'k'+k"
				:label="t.title"
				bar-start="start"
				bar-end="end"
				:bars="[{
					start: t.startDate.toString(),
					end: t.endDate.toString(),
					label: t.title,
					ganttBarConfig: {
						color: colorIsDark(t.getHexColor()) ? 'black' : 'white',
						backgroundColor: t.getHexColor(),
						handles: true,
					}
				}]"
				:highlight-on-hover="true"
			>
			</g-gantt-row>
		</g-gantt-chart>
```

`dateTo` and `dateFrom` are global props with a data object of the range, `theTasks` is an array of task objects from the app.

The tasks are shown as bars in the application, yet I can't drag them around or resize them.

EDIT: I've added an event listener for `@dragend-bar` and it looks like the bar is moved, the change is just not reflected in the gantt chart. I guess I need to manually update the bar object to contain the new dates after dragging them?

**Comment by kolaente** [comment]
I've replaced the gantt row + bars data with a computed property and am now updating the dates in my `dragend-bar` handler. This moves the bars when they are dragged, but I still don't have any visual feedback while moving the bar. Any hints?

**Comment by kolaente** [comment]
Looks like I get the visual feedback when I replace the computed property with a "real" data property.

**Comment by InfectoOne** [comment]
Passing the `bars` array as a constant won't work, since the bars start and end get mutated upon drag. You have to pass a variable/reference instead of a constant array.
