### ISSUE TITLE
Vue-Ganttastic 2.0 (Vue 3 release) - Announcement

### ISSUE THREAD

**Issue by InfectoOne** [InfectoOne/vue-ganttastic#18]
## Vue-Ganttastic 2.0
![image](https://user-images.githubusercontent.com/28678851/146654694-bd004ba5-80b3-4e4c-b7b4-e08c8a29853d.png)
Hello everybody! A little heads-up: Vue-Ganttastic v2.0 is in its final development phase. All functionalities of the previous version have already been implemented, as well as some new features. The focus right now is on thorough testing and preparations for shipping as `npm` package. A `yarn` package is planned too. 

### What's new in Vue-Ganttastic 2 ?
Below is a non-exhaustive list of new features, which have already been implemented. Various improvements and additional features are planned for upcoming minor releases.

- Vue 3 and Typescript support
- improved implementation using Typescript and powerful features provided by Vue 3 (e.g. Composition API)
- now using [Day.js](https://day.js.org/) as the underlying library for date-time manipulation
- new `precision` prop for specifying the displayed time units in the time axis. This enables you to properly display the time axis for wider time ranges (e.g. multiple months)
- slots for customizing how the time units in the time axis are displayed
- minor improvements of the appearance of row labels  

The alpha version is already available as a `npm` package. For more details, please refer to the README in this [branch](https://github.com/InfectoOne/vue-ganttastic/tree/vue-ganttastic-2).

**Estimated release date: December 2021 / January 2022**

**Comment by InfectoOne** [comment]
**Update**: The alpha version is already available as a npm package. For more details, please refer to the README in this [branch](https://github.com/InfectoOne/vue-ganttastic/tree/vue-ganttastic-2).

**Comment by Hugo01** [comment]
Fantastic work
Thank you

**Comment by InfectoOne** [comment]
Update: The beta version has just been published on npm.

https://www.npmjs.com/package/@infectoone/vue-ganttastic

**Comment by InfectoOne** [comment]
Update: Vue Ganttastic v2 has been officially released and merged into `master`.
Check out the official [docs](https://infectoone.github.io/vue-ganttastic/getting-started.html) to get started.
