### ISSUE TITLE
@click-bar

### ISSUE THREAD

**Issue by ambrooo** [InfectoOne/vue-ganttastic#2]
It would be nice to have click event so I can see additional data related to the bar object

**Comment by InfectoOne** [comment]
"`click-bar"` event added in commit c1be46f (Version: 0.9.6)  

More special bar events are planned for future versions. The currently available bar events are:
`mouseenter-bar`  
`mouseleave-bar`  
`mousedown-bar`  
`click-bar`  
`dblclick-bar`  
`contextmenu-bar`  
`dragend-bar`

**Comment by kolaente** [comment]
Any chance to add this back in for the current version? Looks like it has been removed :/

**Comment by InfectoOne** [comment]
> Any chance to add this back in for the current version? Looks like it has been removed :/

I've added this again for you in version [2.0.5](https://www.npmjs.com/package/@infectoone/vue-ganttastic) :kiss:
Fixed in Commit 280f845c5702fdb7bdad3c2b8e1e6c7d9ad9a46d.

**Comment by kolaente** [comment]
Awesome, thank you very much!

**Comment by kolaente** [comment]
Is there a way to prevent the click when it is the result of dragging or resizing the task?
