### ISSUE TITLE
Generate new rows

### ISSUE THREAD

**Issue by pollithor** [InfectoOne/vue-ganttastic#25]
Is it possible to generate new rows dynamically? I've been trying to put all the rows inside the same object using rowBarList  as an array of arrays and v-for, it works except the no-overlap property so I can place a bar over another one.

So this code doesn't work:

`<g-gantt-row v-for="(rowBar, idx) in rowBarList" :key="idx" label="" :bars="rowBar.bars"></g-gantt-row>`

but if I do like this it works:

```
<g-gantt-row label="" :bars="rowBarList[0].bars"></g-gantt-row>
<g-gantt-row label="" :bars="rowBarList[1].bars"></g-gantt-row>
```

Do you have any idea? Thanks in advance.

**Comment by InfectoOne** [comment]
I have just tested dynamic row generation using `v-for` and it works.
How exactly does `rowBarList` look like in your case? Have you tried wrapping the entire rowBarList with `ref()` ?

**Comment by InfectoOne** [comment]
> This is `rowBarlist`
> 
> ```
> const rowBarList = ref([
>       {
>         machine: "Machine SLS",
>         bars: [
>           {
>             startDate: "2022-01-27 13:00",
>             endDate: "2022-01-27 15:00",
>             ganttBarConfig: {
>               // each bar must have a nested ganttBarConfig object ...
>               id: "unique-id-1", // ... and a unique "id" property
>               label: "Slot 1",
>               hasHandles: false,
>               style: {
>                 background: "#0b2f51",
>                 borderRadius: "8px",
>                 color: "#ffffff",
>               },
>             },
>           },
>           {
>             startDate: "2022-01-27 16:00",
>             endDate: "2022-01-27 18:00",
>             ganttBarConfig: {
>               // each bar must have a nested ganttBarConfig object ...
>               id: "unique-id-3", // ... and a unique "id" property
>               label: "Slot 2",
>               hasHandles: false,
>               style: {
>                 background: "#0b2f51",
>                 borderRadius: "8px",
>                 color: "#ffffff",
>               },
>             },
>           },
>         ],
>       },
>       {
>         machine: "Machine FFF Magic",
>         bars: [
>           {
>             startDate: "2022-01-28 17:00",
>             endDate: "2022-01-28 19:00",
>             ganttBarConfig: {
>               // each bar must have a nested ganttBarConfig object ...
>               id: "unique-id-2", // ... and a unique "id" property
>               label: "Slot 3",
>               hasHandles: false,
>               style: {
>                 background: "#0b2f51",
>                 borderRadius: "8px",
>                 color: "#ffffff",
>               },
>             },
>           },
>         ],
>       },
>     ]);
> ```
> 
> I think dynamic generation works, but the dragLimits are not working if I use `v-for` with `g-gantt-row`, then even if I add the no-overlap property, I still can place a bar over another one.

Found the problem. The parent-child/sibling hierarchy within g-gantt-chart looks a bit different than expected when v-for is used. Fix coming soon.
